spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yiyutao/config-repo-demo
server:
  port: 2004
encrypt:
  key: masteryi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/